{"uuid": "46395a5f-ba6f-4e8e-9ec6-e266f5fce775", "children": ["74eb788a-2110-4a07-8ddb-631ef645eb70"], "befores": [{"name": "set_up_Chrome", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x008937D3]\n\t(No symbol) [0x00828B81]\n\t(No symbol) [0x0072B36D]\n\t(No symbol) [0x0074B7EF]\n\t(No symbol) [0x00746FC9]\n\t(No symbol) [0x00781ED5]\n\t(No symbol) [0x00781B2C]\n\t(No symbol) [0x0077B216]\n\t(No symbol) [0x00750D97]\n\t(No symbol) [0x0075253D]\n\tGetHandleVerifier [0x00B0ABF2+2510930]\n\tGetHandleVerifier [0x00B38EC1+2700065]\n\tGetHandleVerifier [0x00B3C86C+2714828]\n\tGetHandleVerifier [0x00943480+645344]\n\t(No symbol) [0x00830FD2]\n\t(No symbol) [0x00836C68]\n\t(No symbol) [0x00836D4B]\n\t(No symbol) [0x00840D6B]\n\tBaseThreadInitThunk [0x75C700F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77C77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77C77B8E+238]\n\n", "trace": "  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Base\\base_Chrome_QA.py\", line 14, in set_up_Chrome\n    self.driver = webdriver.Chrome(service=ChromService(ChromeDriverManager().install()))\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 80, in __init__\n    super().__init__(\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1677095549271, "stop": 1677095555831}], "start": 1677095549271, "stop": 1677095556214}